executors:
    docker-publisher:
        machine: true
jobs:
    build:
        executor: docker-publisher
        steps:
            - checkout
            - run:
                command: ./build.sh
                name: Build
            - run:
                command: ./ci/archive-image.sh ./<< pipeline.parameters.image_archive >>
                name: Archive Docker image
            - persist_to_workspace:
                paths:
                    - ./<< pipeline.parameters.image_archive >>
                    - ./env
                    - ./ci/tag-and-push.sh
                root: .
    deploy:
        executor: docker-publisher
        steps:
            - attach_workspace:
                at: .
            - run:
                command: docker load -i "./<< pipeline.parameters.image_archive >>"
                name: Load archive Docker image
            - run:
                command: ./ci/tag-and-push.sh
                name: Publish Docker Image to Docker Hub
parameters:
    image_archive:
        default: image.tar
        type: string
version: 2.1
workflows:
    build-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - develop
                            - master
            - deploy:
                filters:
                    branches:
                        only: master
                requires:
                    - build
    version: 2.1

